version: '3.8'

services:
  ai-model:
    build: 
      context: .
      dockerfile: Dockerfile
    image: angreg/zions-light-ai:${VERSION:-latest}
    container_name: zions-light-ai
    restart: unless-stopped
    
    ports:
      - "${WEBUI_PORT:-3000}:3000"
      - "${API_PORT:-8000}:8000"
    
    environment:
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}
      - WEBUI_JWT_SECRET_KEY=${WEBUI_JWT_SECRET_KEY}
      - API_SECRET_KEY=${API_SECRET_KEY}
      - ENABLE_SIGNUP=${ENABLE_SIGNUP:-true}
      - GPU_LAYERS=${GPU_LAYERS:-35}
      - CTX_SIZE=${CTX_SIZE:-12288}
      - THREADS=${THREADS:-8}
    
    volumes:
      - ai_model_data:/app/data
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 1G
    
    deploy:
      resources:
        limits:
          memory: 32G
        reservations:
          memory: 16G
          devices:
            - driver: nvidia
              count: ${GPU_COUNT:-1}
              capabilities: [gpu]
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: nginx reverse proxy for production
  nginx-proxy:
    image: nginx:alpine
    container_name: qwen-nginx-proxy
    restart: unless-stopped
    ports:
      - "${PROXY_HTTP_PORT:-80}:80"
      - "${PROXY_HTTPS_PORT:-443}:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - ai-model
    profiles:
      - production

volumes:
  ai_model_data:
    driver: local

networks:
  default:
    driver: bridge
