// F7 — append cost is O(1) in conversation length. FRONTEND_SPEC.md §13:
// "Appending message n+1 writes one record and touches no representation
// whose size grows with n. A test appends to a 2,000-message conversation
// and asserts the bytes written are within a constant factor of the
// message itself."
//
// Bytes written are measured as WAL growth (pg_wal_lsn_diff around the
// exact call under test) rather than wall-clock time — WAL bytes are what
// actually has to reach disk (and, later, pgarchive.py's dump) per write,
// so it is the literal quantity §13 is asking about, not a proxy for it.
//
// This file ALSO measures append_stream_delta's per-call checkpoint cost
// separately and reports the number, per FRONTEND_PLAN.md §3.1: "Per-chunk
// persistence into a jsonb content column rewrites the whole row each time
// under MVCC — O(reply²) per turn. F7 measures O(1) in conversation length
// and will pass regardless, so this cost is invisible to the plan's own
// bar. Decide it explicitly and measure it separately." That measurement is
// reported, not gated — see docs/lanes/L1-store.md for the actual numbers
// and what they mean for the ~500ms checkpoint interval decision.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createTestDb } from './helpers/testdb.js';
import { uuidv7 } from '../../src/lib/server/store/uuid7.js';
import type { TestDb } from './helpers/testdb.js';

/** Bytes of WAL generated by running `fn`, measured as
 *  pg_wal_lsn_diff(after, before) around it on the SAME connection (so no
 *  other backend's writes can land between the two LSN reads on this
 *  session, though background activity — checkpointer, autovacuum on
 *  OTHER relations — can still add noise; see docs/lanes/L1-store.md for
 *  how that was controlled for). Requires the connecting role to have
 *  rights to call pg_current_wal_lsn() — true for the superuser role the
 *  Postgres 16 sidecar runs as (see docker-compose.tests.yml). */
async function measureWalBytes(db: TestDb, fn: () => Promise<void>): Promise<number> {
	const before = (await db.pool.query('SELECT pg_current_wal_lsn() AS lsn')).rows[0].lsn;
	await fn();
	const after = (await db.pool.query('SELECT pg_current_wal_lsn() AS lsn')).rows[0].lsn;
	const { rows } = await db.pool.query('SELECT pg_wal_lsn_diff($1, $2) AS diff', [after, before]);
	return Number(rows[0].diff);
}

/** Bulk-inserts `count` TOTAL messages as one linear chain hanging off the
 *  conversation's EXISTING synthetic root (createConversation already
 *  wrote that root; this appends count-1 more descendants under it via a
 *  single multi-row INSERT, bypassing Store.appendMessage's CAS entirely).
 *  This chain is the FIXTURE the measured append lands on top of — it is
 *  deliberately built by the fastest path available so the test's own
 *  runtime is dominated by the ONE append under measurement, not by 2,000
 *  sequential CAS round trips that are not what F7 is about. */
async function bulkBuildChain(
	db: TestDb,
	convId: string,
	rootId: string,
	userId: string,
	count: number
): Promise<{ leafId: string }> {
	if (count < 1) throw new Error('bulkBuildChain: count must include the existing root (>= 1)');
	const ids: string[] = [rootId];
	const values: string[] = [];
	const params: unknown[] = [];
	let p = 1;
	for (let i = 1; i < count; i++) {
		const id = uuidv7();
		values.push(`($${p++}, $${p++}, $${p++}, $${p++}, $${p++}, $${p++}::jsonb)`);
		params.push(id, convId, ids[ids.length - 1], userId, i % 2 === 0 ? 'assistant' : 'user', JSON.stringify(`bulk-${i}`));
		ids.push(id);
	}
	if (values.length > 0) {
		await db.pool.query(
			`INSERT INTO message (id, conv_id, parent_id, user_id, role, content) VALUES ${values.join(',')}`,
			params
		);
	}
	const leafId = ids[ids.length - 1];
	await db.pool.query('UPDATE conversation SET current_leaf_id = $1 WHERE id = $2', [leafId, convId]);
	return { leafId };
}

test('F7 (scale): append cost is O(1) in conversation length — appending to a 2,000-message conversation costs a constant factor of the message itself', async () => {
	const db = await createTestDb({ prefix: 'f7scale' });
	try {
		const userId = uuidv7();
		const payload = JSON.stringify('x'.repeat(200)); // a modest, realistic single-turn payload

		// Baseline: append #1 onto a FRESH, tiny conversation (10 messages).
		const small = await db.store.createConversation({ userId, systemContent: '"sys"' });
		const { leafId: smallLeaf } = await bulkBuildChain(db, small.conversation.id, small.root.id, userId, 10);
		const smallConvRow = (await db.store.getConversation(small.conversation.id))!;
		const earlyBytes = await measureWalBytes(db, async () => {
			await db.store.appendMessage({
				convId: small.conversation.id,
				parentId: smallLeaf,
				expectedRev: smallConvRow.rev,
				userId,
				role: 'user',
				content: payload
			});
		});

		// The subject: append #1 onto a conversation already at 2,000
		// messages.
		const big = await db.store.createConversation({ userId, systemContent: '"sys"' });
		const { leafId: bigLeaf } = await bulkBuildChain(db, big.conversation.id, big.root.id, userId, 2000);
		const bigConvRow = (await db.store.getConversation(big.conversation.id))!;
		const lateBytes = await measureWalBytes(db, async () => {
			await db.store.appendMessage({
				convId: big.conversation.id,
				parentId: bigLeaf,
				expectedRev: bigConvRow.rev,
				userId,
				role: 'user',
				content: payload
			});
		});

		const contentBytes = Buffer.byteLength(payload, 'utf8');

		// eslint-disable-next-line no-console
		console.log(
			`[F7] contentBytes=${contentBytes} earlyBytes(@10 msgs)=${earlyBytes} lateBytes(@2000 msgs)=${lateBytes} ` +
				`ratio(late/early)=${(lateBytes / earlyBytes).toFixed(2)} ratio(late/content)=${(lateBytes / contentBytes).toFixed(2)}`
		);

		// The O(1)-IN-LENGTH claim: a single N=2000 data point cannot prove
		// independence from N by itself — it takes two points. late must be
		// within a small constant multiple of early, not a multiple of
		// 2000/10=200 the way an O(n) or O(n^2) rewrite would produce.
		assert.ok(
			lateBytes < earlyBytes * 5,
			`append at N=2000 wrote ${lateBytes}B vs ${earlyBytes}B at N=10 (ratio ${(lateBytes / earlyBytes).toFixed(2)}x) — ` +
				`this must stay a small constant, not grow with conversation length`
		);

		// FRONTEND_SPEC.md's literal ask: bytes written for the append
		// itself are within a constant factor of the MESSAGE. One append is
		// one INSERT (id+conv_id+parent_id+user_id+role+content+state,
		// each WAL-logged once) plus one small UPDATE of conversation's
		// leaf pointer, plus the usual per-transaction WAL overhead
		// (commit record, full-page images the first time a page is
		// touched after a checkpoint). 64x the content size comfortably
		// covers that fixed overhead without hiding an actual O(n) leak —
		// see docs/lanes/L1-store.md for the real measured ratio.
		assert.ok(
			lateBytes < contentBytes * 64 + 8192,
			`append at N=2000 wrote ${lateBytes}B for a ${contentBytes}B message — expected within a constant factor`
		);
	} finally {
		await db.close();
	}
});

test('F7 (scale): the streaming-checkpoint rewrite cost — append_stream_delta measured separately, per-call vs per-interval', async () => {
	const db = await createTestDb({ prefix: 'f7checkpoint' });
	try {
		const userId = uuidv7();
		const { conversation, root } = await db.store.createConversation({ userId, systemContent: '"sys"' });

		const CHUNK_COUNT = 120;
		const CHUNK_SIZE = 20; // ~2,400 bytes of final content

		async function simulateStream(checkpointEvery: number, parentId: string, expectedRev: string) {
			const { message } = await db.store.appendMessage({
				convId: conversation.id,
				parentId,
				expectedRev,
				userId,
				role: 'assistant',
				content: '""',
				state: 'streaming'
			});
			let content = '';
			let totalBytes = 0;
			let writes = 0;
			for (let i = 0; i < CHUNK_COUNT; i++) {
				content += 'x'.repeat(CHUNK_SIZE);
				const isLast = i === CHUNK_COUNT - 1;
				if (!isLast && (i + 1) % checkpointEvery !== 0) continue;
				totalBytes += await measureWalBytes(db, async () => {
					await db.store.appendStreamDelta({
						convId: conversation.id,
						messageId: message.id,
						content: JSON.stringify(content),
						final: isLast
					});
				});
				writes++;
			}
			return { totalBytes, writes, finalMessageId: message.id };
		}

		// Per-token: one checkpoint write per chunk — the exact footgun
		// FRONTEND_PLAN.md §3.1 names ("per-chunk persistence ... rewrites
		// the whole row each time under MVCC — O(reply²) per turn").
		const perToken = await simulateStream(1, root.id, conversation.rev);

		// Per-~500ms-interval, approximated here as "every 15th chunk" —
		// the actual interval is real time, not a chunk count, but the
		// POINT being measured is call frequency, and this keeps the test
		// deterministic rather than clock-dependent. Run as a SIBLING of
		// the per-token stream (both children of the same root), reached
		// by moving the leaf back explicitly first.
		const convAfterFirst = (await db.store.getConversation(conversation.id))!;
		const { rev: revAtRoot } = await db.store.selectLeaf({
			convId: conversation.id,
			targetMessageId: root.id,
			expectedRev: convAfterFirst.rev
		});
		const perInterval = await simulateStream(15, root.id, revAtRoot);

		const finalContentBytes = CHUNK_COUNT * CHUNK_SIZE;
		// eslint-disable-next-line no-console
		console.log(
			`[F7 checkpoint] finalContentBytes=${finalContentBytes} ` +
				`perToken: writes=${perToken.writes} totalBytes=${perToken.totalBytes} ` +
				`perInterval(every 15): writes=${perInterval.writes} totalBytes=${perInterval.totalBytes} ` +
				`blowup(perToken/perInterval)=${(perToken.totalBytes / perInterval.totalBytes).toFixed(2)}x`
		);

		// Reported, not gated on a tight bound (this is real WAL noise on a
		// small number of samples) — but the DIRECTION must hold: batching
		// into fewer, larger writes must not cost MORE than writing every
		// token individually, or the whole premise (checkpoint on an
		// interval, not per token) would be backwards.
		assert.ok(
			perInterval.totalBytes < perToken.totalBytes,
			'checkpointing on an interval must write fewer total bytes than checkpointing every chunk'
		);
		assert.ok(perInterval.writes < perToken.writes);
	} finally {
		await db.close();
	}
});
