#!/usr/bin/env python3
"""Word-ban check for the pod (revision __REVISION__). Generated by `wordban.py release`; do not edit by hand.

Sends one prompt that asks for the banned words, three ways:
  A  straight to vLLM (:8000) with NO ban            -> the grammar should refuse the reply (proves the prompt works)
  B  straight to vLLM (:8000) WITH the saved ban     -> the saved grammar must accept the reply
  C  through the compactor (:8080) WITH the ban      -> the same (the production hop)
The ban is read from the model's saved OpenWebUI settings, READ-ONLY (one SELECT; nothing is written). Each reply
is judged by the SAVED grammar itself (a small interpreter below), so this script never goes stale.
C uses its own test conversation id (itest-wordban-check), never hers.   Usage: python3 word-ban-check.py [webui.db]
PASS needs all three: A writes a banned word (the control), B and C write none. A truncated or corrupt saved value
is reported as such (re-paste), never as a traceback."""
import bisect
import hashlib
import json
import sqlite3
import sys
import time
import urllib.request

REVISION = __REVISION__
EXPECTED = "__SHA__"
MODEL = __MODEL__
PROMPT = __PROMPT__
ALLOWED = __ALLOWED__
DB = sys.argv[1] if len(sys.argv) > 1 else "/data/openwebui/webui.db"


# ---------------- a small interpreter for the grammar's EBNF (the shape wordban emits) ----------------
def _cc_char(s, i):
    if s[i] == "\\":
        if s[i + 1] == "u":
            return int(s[i + 2:i + 6], 16), i + 6
        if s[i + 1] == "U":
            return int(s[i + 2:i + 10], 16), i + 10
        return ord(s[i + 1]), i + 2
    return ord(s[i]), i + 1


def _tokens(s):
    toks, i = [], 0
    while i < len(s):
        ch = s[i]
        if ch.isspace():
            i += 1
        elif ch == "|":
            toks.append(("|",))
            i += 1
        elif s.startswith('""', i):
            toks.append(("eps",))
            i += 2
        elif ch == "[":
            i += 1
            lo, hi = [], []
            while s[i] != "]":
                a, i = _cc_char(s, i)
                b = a
                if s[i] == "-" and s[i + 1] != "]":
                    b, i = _cc_char(s, i + 1)
                lo.append(a)
                hi.append(b)
            i += 1
            order = sorted(range(len(lo)), key=lambda k: lo[k])
            toks.append(("cc", ([lo[k] for k in order], [hi[k] for k in order])))
        else:
            j = i
            while j < len(s) and (s[j].isalnum() or s[j] == "_"):
                j += 1
            toks.append(("id", s[i:j]))
            i = j
    return toks


class Grammar:
    def __init__(self, ebnf):
        rules = {}
        for line in ebnf.splitlines():
            if "::=" not in line:
                continue
            name, _, body = line.partition("::=")
            alts, cur = [], []
            for t in _tokens(body):
                if t[0] == "|":
                    alts.append(cur)
                    cur = []
                else:
                    cur.append(t)
            alts.append(cur)
            rules[name.strip()] = alts
        atoms = {n: a[0][0][1] for n, a in rules.items() if len(a) == 1 and len(a[0]) == 1 and a[0][0][0] == "cc"}
        self.info = {}
        for n, alts in rules.items():
            if n in atoms:
                continue
            eps, acc, edges = [], False, []
            for a in alts:
                if len(a) == 1 and a[0][0] == "eps":
                    acc = True
                elif len(a) == 1:
                    eps.append(a[0][1])
                else:
                    edges.append((a[0][1] if a[0][0] == "cc" else atoms[a[0][1]], a[1][1]))
            self.info[n] = (eps, acc, edges)
        if "root" not in self.info or any(t not in self.info for e, _a, ed in self.info.values()
                                          for t in list(e) + [x[1] for x in ed]):
            raise ValueError("incomplete grammar")

    def _closure(self, names):
        seen, st = set(), list(names)
        while st:
            x = st.pop()
            if x not in seen:
                seen.add(x)
                st += self.info[x][0]
        return seen

    def refused_at(self, text):
        """None if the whole text (then end of reply) is allowed; else the index where it is refused"""
        cur = self._closure(["root"])
        for i, ch in enumerate(text):
            cp, nxt = ord(ch), set()
            for r in cur:
                for (lo, hi), t in self.info[r][2]:
                    k = bisect.bisect_right(lo, cp) - 1
                    if k >= 0 and cp <= hi[k]:
                        nxt.add(t)
            cur = self._closure(nxt)
            if not cur:
                return i
        return None if any(self.info[r][1] for r in cur) else len(text)


def word_at(text, i):
    a = b = min(i, len(text) - 1)
    while a > 0 and (text[a - 1].isalnum() or text[a - 1] in "'’-_"):
        a -= 1
    while b < len(text) and (text[b].isalnum() or text[b] in "'’-_"):
        b += 1
    return text[a:b + 1].strip()


CUT = ("the saved value is truncated or corrupt (the paste was cut short?). Re-paste "
       "word-ban-structured_outputs.value.txt into the structured_outputs row, Save & Update, and run this again.")
con = sqlite3.connect(f"file:{DB}?mode=ro", uri=True, timeout=10)
row = con.execute("select params from model where id=?", (MODEL,)).fetchone()
con.close()
cp = (json.loads(row[0]) if row else {}).get("custom_params") or {}
so = cp.get("structured_outputs")
if not so:
    sys.exit("structured_outputs is not saved on the model yet - do step 1 first, then Save & Update")
raw = so if isinstance(so, str) else json.dumps(so)
print(f"saved value: {len(raw)} characters")
try:
    so = json.loads(so) if isinstance(so, str) else so
    grammar = so["grammar"]
except Exception:                                                    # noqa: BLE001
    print(f"saved grammar != revision {REVISION}: " + CUT)
    print("\nRESULT: FAIL (see above)")
    sys.exit(1)
got = hashlib.sha256(grammar.encode()).hexdigest()
print(f"saved grammar: {len(grammar)} chars, sha256 {got[:16]}... "
      + (f"= revision {REVISION}, pasted intact" if got == EXPECTED
         else f"!= revision {REVISION} (an older revision, or the paste was cut short)"))
try:
    G = Grammar(grammar)
    G.refused_at("test")
except Exception:                                                    # noqa: BLE001
    print(CUT)
    print("\nRESULT: FAIL (see above)")
    sys.exit(1)


def ask(port, extra, headers):
    body = {"model": MODEL, "messages": [{"role": "user", "content": PROMPT}],
            "max_tokens": 450, "temperature": 0, "stream": False, **extra}
    req = urllib.request.Request(f"http://localhost:{port}/v1/chat/completions", data=json.dumps(body).encode(),
                                 headers={"Content-Type": "application/json", **headers})
    t = time.time()
    with urllib.request.urlopen(req, timeout=900) as r:
        ch = json.load(r)["choices"][0]
        return ch["message"]["content"] or "", ch.get("finish_reason"), time.time() - t


ok = got == EXPECTED
for label, port, extra, hdr, want in [
    ("A vLLM, no ban       ", 8000, {}, {}, False),
    ("B vLLM + ban         ", 8000, {"structured_outputs": so}, {}, True),
    ("C compactor + ban    ", 8080, {"structured_outputs": so}, {"X-Conversation-Id": "itest-wordban-check"}, True),
]:
    try:
        out, finish, dt = ask(port, extra, hdr)
    except Exception as e:                                           # noqa: BLE001
        body = getattr(e, "read", lambda: b"")().decode(errors="replace")[:300]
        print(f"{label} REQUEST FAILED: {e} {body}")
        ok = False
        continue
    at = G.refused_at(out)
    if at is not None and at >= len(out) and finish == "length":
        at = None                  # stopped at max_tokens in the middle of a word: unfinished, not a banned word
        note = " (stopped at max_tokens mid-word)"
    else:
        note = ""
    kept = [w for w in ALLOWED if w.lower() in out.lower()]
    verdict = ("no banned word (the grammar accepts it)" + note) if at is None else f"BANNED WORD near {word_at(out, at)!r}"
    print(f"{label} {dt:5.1f}s  {verdict}  | allowed words it wrote: {kept}")
    print("      " + out.replace("\n", " ")[:600])
    if want and at is not None:
        ok = False
    if not want and at is None:
        ok = False
        print("      CONTROL FAILED: without the ban the model wrote no banned word, so B and C prove nothing.")
print("\nRESULT:", "PASS" if ok else "FAIL (see above)")
sys.exit(0 if ok else 1)
