// Helpers for F5's adversarial suite (docs/lanes/L1-store.md). Every
// function here writes via raw SQL against db.pool / db.rawPool, never via
// Store's own write API — the point of F5 is to build tree SHAPES the
// store's public API could never produce (multi-root, dangling parents,
// wholly unreachable subtrees), which is only possible after defeating a
// specific constraint first. Each fixture's own test proves, inline, that
// the constraint it defeats would otherwise have refused the exact insert
// being planted — see f5-adversarial.test.ts's `assert.rejects(...)` calls
// that run BEFORE each `dropConstraint`/`dropIndex` call below.
//
// Nothing here restores what it drops. The schema is a fresh, randomly
// named, throwaway one per test (see helpers/testdb.ts) and is DROP
// SCHEMA ... CASCADE'd whole in db.close() — there is nothing to repair and
// repairing it would not make the fixture "safe to reuse" in any way that
// matters.

import type { TestDb } from '../helpers/testdb.js';
import { uuidv7 } from '../../../src/lib/server/store/uuid7.js';

export interface SeededChain {
	rootId: string;
	leafId: string;
	/** root..leaf, in order. */
	ids: string[];
}

/** Drops a named CHECK/FK/UNIQUE constraint on a table in THIS fixture's
 *  schema. Uses db.rawPool (no search_path pinned) so the DDL is
 *  schema-qualified explicitly — db.schema is generated by randomSchema()
 *  (helpers/testdb.ts), never user input, so string interpolation here is
 *  safe. */
export async function dropConstraint(db: TestDb, table: string, constraint: string): Promise<void> {
	await db.rawPool.query(`ALTER TABLE "${db.schema}".${table} DROP CONSTRAINT ${constraint}`);
}

/** Drops a named index (message_one_root_per_conv is a partial UNIQUE
 *  INDEX, not a table constraint, so it needs DROP INDEX rather than DROP
 *  CONSTRAINT). */
export async function dropIndex(db: TestDb, index: string): Promise<void> {
	await db.rawPool.query(`DROP INDEX "${db.schema}".${index}`);
}

/** Inserts one linear chain of `length` messages — a NEW root (parent_id
 *  NULL) plus length-1 descendants — directly, bypassing
 *  Store.appendMessage's CAS and current_leaf_id/rev bookkeeping entirely.
 *  Every call is deliberately building an EXTRA root alongside (or instead
 *  of) the conversation's own synthetic one, which requires
 *  message_one_root_per_conv to already be gone — fixtures call this only
 *  after dropIndex(db, 'message_one_root_per_conv'). Fixtures need chains
 *  that never touch the leaf pointer at all — e.g. four of the standing
 *  case's five trees are never the current branch and must not
 *  participate in any CAS. */
export async function insertChain(
	db: TestDb,
	convId: string,
	userId: string,
	length: number
): Promise<SeededChain> {
	if (length < 1) throw new Error('insertChain: length must be >= 1');
	const ids: string[] = [];
	for (let i = 0; i < length; i++) {
		const id = uuidv7();
		const parentId = i === 0 ? null : ids[i - 1];
		await db.pool.query(
			`INSERT INTO message (id, conv_id, parent_id, user_id, role, content)
			 VALUES ($1, $2, $3, $4, $5, $6::jsonb)`,
			[id, convId, parentId, userId, i === 0 ? 'system' : 'user', JSON.stringify(`node-${i}`)]
		);
		ids.push(id);
	}
	return { rootId: ids[0], leafId: ids[ids.length - 1], ids };
}

/** Points current_leaf_id directly, bypassing selectLeaf's reachability
 *  predicate and rev CAS entirely — fixtures use this specifically to build
 *  states selectLeaf() could never reach (e.g. a leaf inside an unreachable
 *  subtree), which is the point. */
export async function setCurrentLeaf(db: TestDb, convId: string, leafId: string): Promise<void> {
	await db.pool.query(`UPDATE conversation SET current_leaf_id = $1 WHERE id = $2`, [leafId, convId]);
}

/** Points current_leaf_id at NULL directly. Legal per the column's own
 *  definition (nullable; conversation_leaf_fk is a composite FK, and a
 *  MATCH SIMPLE composite FK with any NULL member is vacuously satisfied —
 *  Postgres never even evaluates it), and selectLeaf() could never produce
 *  this state on its own (F2, docs/lanes/L1-store.md). */
export async function setCurrentLeafNull(db: TestDb, convId: string): Promise<void> {
	await db.pool.query(`UPDATE conversation SET current_leaf_id = NULL WHERE id = $1`, [convId]);
}
